/*
 ZWeb.js v0.0.1
 (c) 2017 Zyao89
 Released under the MIT License.
*/
(function(c,f){if("undefined"===typeof c)throw"not find window...";"undefined"===typeof c.__ZWeb__&&(f=f(c,"ZWeb"),c.__ZWeb__=new f)})(window,function(c,f){var g={UUID:void 0,Promise:void 0};(function(a){function b(){this.id=this.createUUID()}b.prototype.valueOf=function(){return this.id};b.prototype.toString=function(){return this.id};b.prototype.createUUID=function(){var a=new Date(1582,10,15,0,0,0,0),c=(new Date).getTime()-a.getTime(),a=b.getIntegerBits(c,0,31),k=b.getIntegerBits(c,32,47),c=b.getIntegerBits(c,
48,59)+"1",n=b.getIntegerBits(b.rand(4095),0,7),f=b.getIntegerBits(b.rand(4095),0,7),e=b.getIntegerBits(b.rand(8191),0,7)+b.getIntegerBits(b.rand(8191),8,15)+b.getIntegerBits(b.rand(8191),0,7)+b.getIntegerBits(b.rand(8191),8,15)+b.getIntegerBits(b.rand(8191),0,15);return a+"-"+k+"-"+c+"-"+n+f+"-"+e};b.getIntegerBits=function(a,c,k){a=b.returnBase(a,16);var d=[],h="",e;for(e=0;e<a.length;e++)d.push(a.substring(e,e+1));for(e=Math.floor(c/4);e<=Math.floor(k/4);e++)h=d[e]&&""!=d[e]?h+d[e]:h+"0";return h};
b.returnBase=function(a,b){var c="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");if(a<b)b=c[a];else{var d=""+Math.floor(a/b);a-=d*b;b=d>=b?this.returnBase(d,b)+c[a]:c[d]+c[a]}return b};b.rand=function(a){return Math.floor(Math.random()*a)};a.UUID=b})(g);(function(a){var b=function(){this.callbacks=[]};b.prototype={construct:b,resolve:function(a){this.complete("resolve",a)},reject:function(a){this.complete("reject",a)},complete:function(a,b){for(;this.callbacks[0];){var c=this.callbacks.shift()[a];
c&&c(b)}},then:function(a,b){this.callbacks.push({resolve:a,reject:b});return this}};a.Promise=b})(g);var l=function(a,b){this.mapRequireQueue={};this.mapMessageQueue={};this.mapDatabaseQueue={};this.szFrameworkUUID=a;this.OS=b.OS;this.Version=b.Version;this.InternalName=b.InternalName;this.ExposedName=b.ExposedName;this.__onFuncCallBackMap__={};this.print("Info",JSON.stringify(b))};l.prototype={createUUID:function(){return(new g.UUID).id},saveData:function(a,b){a={Sequence:this.createUUID(),Data:{Key:a,
Value:b}};b=new g.Promise;this.mapDatabaseQueue[a.Sequence]=b;this.callInterOS("saveData",a);return b},loadData:function(a){a={Sequence:this.createUUID(),Data:a};var b=new g.Promise;this.mapDatabaseQueue[a.Sequence]=b;this.callInterOS("loadData",a);return b},databaseCallback:function(a){var b=a.Sequence,c=this.mapDatabaseQueue[b];"undefined"!==typeof c&&(delete this.mapDatabaseQueue[b],"success"===a.Result?c.resolve(a.Data):c.reject(a.Data))},showLoading:function(){this.callInterOS("showLoading")},
hideLoading:function(){this.callInterOS("hideLoading")},tip:function(a){this.callInterOS("tip",a)},require:function(a,b,c,h){a={Sequence:this.createUUID(),Url:a,Method:b,Data:c,Type:h||"json"};b=new g.Promise;this.mapRequireQueue[a.Sequence]=b;this.callInterOS("onRequire",a);return b},requireCallback:function(a){var b=a.Sequence,c=this.mapRequireQueue[b];"undefined"!==typeof c&&(delete this.mapRequireQueue[b],"success"===a.Result?c.resolve(a.Data):c.reject(a.Data))},message:function(a,b){a={Sequence:this.createUUID(),
Cmd:a,Data:b};b=new g.Promise;this.mapMessageQueue[a.Sequence]=b;this.callInterOS("onMessage",a);return b},messageCallback:function(a){var b=a.Sequence,c=this.mapMessageQueue[b];"undefined"!==typeof c&&(delete this.mapMessageQueue[b],"success"===a.Result?c.resolve(a.Data):c.reject(a.Data))},destroy:function(){this.callInterOS("onDestroy")},callInterOS:function(a,b){this.callOS(a,b,this.InternalName)},callOS:function(a,b,d){"undefined"===typeof d&&(d=this.ExposedName);switch(this.OS){case "ANDROID":if(c[d]&&
c[d][a])if("undefined"===typeof b)c[d][a](this.szFrameworkUUID);else if("object"===typeof b)c[d][a](this.szFrameworkUUID,JSON.stringify(b));else c[d][a](this.szFrameworkUUID,b);else this.print(a+" : "+this.szFrameworkUUID+"\uff1a Android \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");break;case "IOS":c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers[d]?(a={Method:a,FrameworkID:this.szFrameworkUUID,Data:JSON.stringify(b)},"undefined"===typeof b&&delete a.Data,c.webkit.messageHandlers[d].postMessage(a)):
this.print(a+" : "+this.szFrameworkUUID+"\uff1a IOS \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");break;case "WEB":this.print(a+" : "+this.szFrameworkUUID+"\uff1a Web \u63a5\u53e3\u8c03\u7528...");break;default:this.print("init callOS error, \u56de\u8c03\u5931\u8d25\u3002")}},exceptionOS:function(a,b){switch(this.OS){case "ANDROID":if(c[this.InternalName]&&c[this.InternalName].onException)if("undefined"===typeof b)c[this.InternalName].onException(this.szFrameworkUUID,a,"");else if("object"===typeof oData)c[this.InternalName].onException(this.szFrameworkUUID,
a,JSON.stringify(b));else c[this.InternalName].onException(this.szFrameworkUUID,a,b);else this.print("onException : "+this.szFrameworkUUID+"\uff1a Android \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");break;case "IOS":c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers[this.InternalName]?(a={Method:"onException",FrameworkID:this.szFrameworkUUID,ErrorCode:a,Data:JSON.stringify(b)},c.webkit.messageHandlers[this.InternalName].postMessage(a)):this.print("onException : "+this.szFrameworkUUID+"\uff1a IOS \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");
break;case "WEB":this.print("onException : "+this.szFrameworkUUID+"\uff1a Web \u63a5\u53e3\u8c03\u7528...");break;default:this.print("init callOS error, \u56de\u8c03\u5931\u8d25\u3002")}},print:function(){var a="Debug",b=arguments[0];2===arguments.length&&(a=arguments[0],b=arguments[1]);a={Type:a,Msg:b};console.info(a);switch(this.OS){case "ANDROID":if(c[this.InternalName]&&c[this.InternalName].onLog)c[this.InternalName].onLog(this.szFrameworkUUID,JSON.stringify(a));else console.error("onLog : "+
this.szFrameworkUUID+"\uff1a Android \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");break;case "IOS":c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers[this.InternalName]?(b={Method:"onLog",FrameworkID:this.szFrameworkUUID,Data:JSON.stringify(a)},c.webkit.messageHandlers[this.InternalName].postMessage(b)):console.error("onException : "+this.szFrameworkUUID+"\uff1a IOS \u63a5\u53e3\u8c03\u7528\u5f02\u5e38...");break;case "WEB":console.error("onLog : "+this.szFrameworkUUID+"\uff1a Web \u63a5\u53e3\u8c03\u7528...");
break;default:console.error("Call print error...")}},on:function(a,b){this.__onFuncCallBackMap__[a]=b},dispatchCall:function(a,b){(a=this.__onFuncCallBackMap__[a])&&"function"===typeof a&&a(b)}};var m=function(){this.szFrameworkUUID=0;this.OS="WEB";this.ZWebSDK=this.ExposedName=this.InternalName=this.Version=void 0};m.prototype={initFramework:function(a,b){this.szFrameworkUUID=a;this.OS=b.OS;this.Version=b.Version;this.InternalName=b.InternalName;this.ExposedName=b.ExposedName;c[f+"SDK"]=this.ZWebSDK=
new l(a,b);this.ZWebSDK.callInterOS("onCreated",function(){var a=0,b=0;c.innerWidth?a=c.innerWidth:document.body&&document.body.clientWidth&&(a=document.body.clientWidth);c.innerHeight?b=c.innerHeight:document.body&&document.body.clientHeight&&(b=document.body.clientHeight);document.documentElement&&document.documentElement.clientHeight&&document.documentElement.clientWidth&&(b=document.documentElement.clientHeight,a=document.documentElement.clientWidth);return{Width:a,Height:b}}());a=void 0;c.Vue&&
(a=c.Vue["__"+f+"_Dispatch_Ready__"]);a&&"function"===typeof a||(a=c["__"+f+"_Dispatch_Ready__"]);a&&"function"===typeof a&&a()},requireCallback:function(a,b){this.ZWebSDK.requireCallback(b)},messageCallback:function(a,b){this.ZWebSDK.messageCallback(b)},databaseCallback:function(a,b){this.ZWebSDK.databaseCallback(b)},callReceiver:function(a,b,c){this.ZWebSDK.dispatchCall(b,c)},goBack:function(a){this.ZWebSDK.print("goBack \u88ab\u8c03\u7528\u4e86...");c.history.go(-1)},goForward:function(a){this.ZWebSDK.print("goForward \u88ab\u8c03\u7528\u4e86...");
c.history.go(1)},refresh:function(a){this.ZWebSDK.print("refresh \u88ab\u8c03\u7528\u4e86...");c.location.reload()}};return m});